export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_THEATERS = "CREATE_THEATERS";
export const GET_THEATERS = "GET_THEATERS";
export const UPDATE_THEATERS = "UPADTE_THEATERS";
export const DELETE_THEATERS = "DELETE_THEATERS";
export const DELETE_ALL_THEATERS = "DELETE_ALL_THEATERS";



//BOOK
export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOKS_BY_ID = "GET_BOOKS_BY_ID";
export const CREATE_BOOK = "CREATE_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";

//order
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_BY_ID = "GET_ORDERS_BY_ID";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";

//orderitems
export const GET_ORDERITEMS = "GET_ORDERITEMS";
export const GET_ORDERSITEMS_BY_ID = "GET_ORDERSITEMS_BY_ID";
export const CREATE_ORDERITEM = "CREATE_ORDERITEM";
export const UPDATE_ORDERITEM = "UPDATE_ORDERITEM";
export const DELETE_ORDERITEM = "DELETE_ORDERITEM";

//genre

export const GET_GENRES= "GET_GENRES";
export const GET_GENRES_BY_ID = "GET_GENRES_BY_ID";
export const CREATE_GENRE= "CREATE_GENRE";
export const UPDATE_GENRE = "UPDATE_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";